-- ============================================
-- Product Purchasing System - Schema DDL (PostgreSQL)
-- ============================================
--
-- Migración de src/main/resources/sql/schema.sql (MySQL) a PostgreSQL.
--
-- NOTA: Con hibernate.hbm2ddl.auto=update, Hibernate crea/actualiza
-- las tablas automáticamente (ver application.yml). Este script es de
-- referencia y sirve para ambientes donde se necesite DDL manual.
--
-- Diferencias frente al script MySQL original:
--   - AUTO_INCREMENT           -> GENERATED BY DEFAULT AS IDENTITY
--   - ENUM(...)                -> VARCHAR(n) + CHECK (...)
--   - INDEX dentro de CREATE   -> CREATE INDEX aparte (no soportado inline en PG)
--   - ENGINE/CHARSET/COLLATE   -> eliminado (no aplica en PostgreSQL)
--   - ON UPDATE CURRENT_TIMESTAMP -> trigger set_updated_at()
--
-- ============================================
-- Crear base de datos y rol de aplicación
-- ============================================
-- Estas sentencias deben ejecutarse conectado a la base "postgres"
-- (no pueden ir dentro de una transacción junto con el resto del script).
-- Ejecutar por separado, por ejemplo:
--   psql -U postgres -c "CREATE DATABASE pps_db ENCODING 'UTF8';"
--   psql -U postgres -c "CREATE ROLE user_pps LOGIN PASSWORD 'YOUR_SECURE_PASSWORD';"
--   psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE pps_db TO user_pps;"
--
-- CREATE DATABASE pps_db ENCODING 'UTF8';
-- CREATE ROLE user_pps LOGIN PASSWORD 'YOUR_SECURE_PASSWORD';
-- GRANT ALL PRIVILEGES ON DATABASE pps_db TO user_pps;

-- ============================================
-- Función auxiliar para columnas updated_at
-- ============================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- Tabla: roles
-- ============================================
CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_role_name ON roles (name);

-- ============================================
-- Tabla: users
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_user_status ON users (status);

-- ============================================
-- Tabla: addresses
-- ============================================
CREATE TABLE IF NOT EXISTS addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type IN ('SHIPPING', 'BILLING')),
    line1 VARCHAR(255) NOT NULL,
    line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_address_user ON addresses (user_id);
CREATE INDEX IF NOT EXISTS idx_address_type ON addresses (type);

-- ============================================
-- Tabla: categories
-- ============================================
CREATE TABLE IF NOT EXISTS categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (category_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_category_slug ON categories (slug);
CREATE INDEX IF NOT EXISTS idx_category_parent ON categories (parent_id);

-- ============================================
-- Tabla: products
-- ============================================
CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_qty INT NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (category_id)
);

CREATE INDEX IF NOT EXISTS idx_product_sku ON products (sku);
CREATE INDEX IF NOT EXISTS idx_product_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_product_active ON products (is_active);

-- ============================================
-- Tabla: user_sessions
-- ============================================
CREATE TABLE IF NOT EXISTS user_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    session_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_session_token ON user_sessions (session_token);
CREATE INDEX IF NOT EXISTS idx_session_user ON user_sessions (user_id);

-- ============================================
-- Tabla: carts
-- ============================================
CREATE TABLE IF NOT EXISTS carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    session_id BIGINT,
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CONVERTED', 'ABANDONED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_carts_session FOREIGN KEY (session_id) REFERENCES user_sessions (session_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_cart_user ON carts (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_status ON carts (status);

DROP TRIGGER IF EXISTS trg_carts_updated_at ON carts;
CREATE TRIGGER trg_carts_updated_at
    BEFORE UPDATE ON carts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- ============================================
-- Tabla: cart_items
-- ============================================
CREATE TABLE IF NOT EXISTS cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_item_cart ON cart_items (cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_item_product ON cart_items (product_id);

-- ============================================
-- Tabla: order_statuses
-- ============================================
CREATE TABLE IF NOT EXISTS order_statuses (
    order_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- ============================================
-- Tabla: orders
-- ============================================
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    order_status_id BIGINT NOT NULL,
    shipping_address_id BIGINT NOT NULL,
    billing_address_id BIGINT NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) NOT NULL,
    shipping_cost DECIMAL(10, 2) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_status FOREIGN KEY (order_status_id) REFERENCES order_statuses (order_status_id),
    CONSTRAINT fk_orders_shipping_address FOREIGN KEY (shipping_address_id) REFERENCES addresses (address_id),
    CONSTRAINT fk_orders_billing_address FOREIGN KEY (billing_address_id) REFERENCES addresses (address_id)
);

CREATE INDEX IF NOT EXISTS idx_order_number ON orders (order_number);
CREATE INDEX IF NOT EXISTS idx_order_user ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON orders (order_status_id);
CREATE INDEX IF NOT EXISTS idx_order_created ON orders (created_at);

-- ============================================
-- Tabla: order_items
-- ============================================
CREATE TABLE IF NOT EXISTS order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    line_total DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE INDEX IF NOT EXISTS idx_order_item_order ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product ON order_items (product_id);

-- ============================================
-- Tabla: payment_methods
-- ============================================
CREATE TABLE IF NOT EXISTS payment_methods (
    payment_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- ============================================
-- Tabla: payment_statuses
-- ============================================
CREATE TABLE IF NOT EXISTS payment_statuses (
    payment_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- ============================================
-- Tabla: payments
-- ============================================
CREATE TABLE IF NOT EXISTS payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_method_id BIGINT NOT NULL,
    payment_status_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD' CHECK (currency IN ('USD', 'COP', 'EUR')),
    transaction_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods (payment_method_id),
    CONSTRAINT fk_payments_status FOREIGN KEY (payment_status_id) REFERENCES payment_statuses (payment_status_id)
);

CREATE INDEX IF NOT EXISTS idx_payment_order ON payments (order_id);
CREATE INDEX IF NOT EXISTS idx_payment_transaction ON payments (transaction_id);
